#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update -y
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
sudo touch /var/www/html/Custom-404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/Custom-404.html
sudo vi /etc/nginx/sites-enabled/default

server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
        }
	location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
"
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "$config" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
